### PR TITLE
Deduplicating licenses in article info

### PR DESCRIPTION
**Pull request by giorgiosironi**
Adding article 13343 as fixture and generating license info over it.

Not doing anything for now for the problem of the duplicated HTML element id.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
@nlisgo what do you think? Don't want to overcomplicate this.

**Comment by nlisgo** [comment]
The intention was that there only be a single `<div id="article-info-license">`. If we can amend the `jats-to-html.xsl` to ensure that there is no duplicate of this id in all of the html then I think this is the cleanest way to approach it.

Something like this should work:

```
 <!-- permissions -->
    <xsl:template match="permissions">
        <div>
            <xsl:choose>
                <xsl:when test="parent::article-meta">
                    <xsl:attribute name="id">
                        <xsl:value-of select="'article-info-license'"/>
                    </xsl:attribute>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:attribute name="class">
                        <xsl:value-of select="'copyright-and-license'"/>
                    </xsl:attribute>
                </xsl:otherwise>
            </xsl:choose>
            <xsl:apply-templates/>
            <xsl:if test="parent::article-meta">
                <xsl:apply-templates select="//body//permissions"/>
            </xsl:if>
        </div>
    </xsl:template>
```

**Comment by giorgiosironi** [comment]
Updated with your XSL addition, deduplication in the code is not necessary anymore for the tests to pass.

**Comment by nlisgo** [comment]
Looks good to me

**Pull request merged**
